defaults: &defaults
  working_directory: ~/analytics.js-core
  docker:
    - image: circleci/node:12-browsers

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - restore_cache:
          key: yarn-dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: make test
      - store_test_results:
          path: junit-reports
  coverage:
    <<: *defaults
    steps:
      - checkout
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - restore_cache:
          key: yarn-dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn run tsc
      - run: yarn run karma start karma.conf.coverage.js
      - store_test_results:
          path: junit-reports
      - run: yarn run codecov
      - persist_to_workspace:
          root: .
          paths:
            - .
  snyk:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: yarn run snyk test --severity-threshold=high
      - run: yarn run snyk monitor

  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - run: yarn add -G tsc
      - run: yarn tsc --declaration
      - run: npm publish .

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - coverage:
          filters:
            tags:
              only: /.*/
      - snyk:
          context: snyk
          requires:
            - coverage
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.+)?/
            branches:
              ignore: /.*/
